name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write # Grants the GITHUB_TOKEN write permission to the pages repository
            id-token: write # Grants the GITHUB_TOKEN write permission to the ID token

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '24' # Use a recent stable Node.js version

            - name: Install dependencies
              run: npm ci

            - name: Build SvelteKit static site
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build # The directory where SvelteKit outputs the static files
